name: sexy_api_client
description: A simple wrapper around Google's http module for easily making Query String API calls.
version: 0.0.6+6
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.4
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec+